apiVersion: apps/v1
kind: Deployment
metadata:
  name: wellbeingapp-deployment
spec:
  selector:
    matchLabels:
      app: wellbeingapp
  template:
    metadata:
      labels:
        app: wellbeingapp
    spec:
      containers:
      - name: wellbeingapp
        image: wellbeing
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
